name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  test-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install
    - name: Run Jest tests
      run: npx jest --verbose
    - name: Build (optional)
      run: npm run build || echo "No build step defined"
    - name: Deploy to Heroku (example)
      if: success()
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        git remote add heroku https://git.heroku.com/your-app-name.git
        git push heroku main